byears <- unique(bData$year)
bemissions <- with(bData, tapply(Emissions, year, sum, rm.na=TRUE))
yrng=c(1500,4500)
plot(byears, bemissions, pch=19, col="dark green", type="b", ylim=yrng)
library(dplyr)
bg <- group_by(bData, type)
with(bg, tapply(Emissions, type, sum, rm.na=TRUE))
with(bg, tapply(Emissions, year, sum, rm.na=TRUE))
with(subset(bg,year==1999), tapply(Emissions, type, sum, rm.na=TRUE))
e1999 <- with(subset(bg,year==1999), tapply(Emissions, type, sum, rm.na=TRUE))
e2002 <- with(subset(bg,year==2002), tapply(Emissions, type, sum, rm.na=TRUE))
e2005 <- with(subset(bg,year==2005), tapply(Emissions, type, sum, rm.na=TRUE))
e2008 <- with(subset(bg,year==2008), tapply(Emissions, type, sum, rm.na=TRUE))
df <- as.data.frame(e1999)
df <- cbind(df, as.data.frame(e2002))
df <- cbind(df, as.data.frame(e2005))
df <- cbind(df, as.data.frame(e2008))
par(mfrow=c(2,2), mar=c(4,4,2,1))
plot(byears, df["NON-ROAD",], pch=19, type="b", col="dark red", ylab="NON-ROAD", xlab="Years")
plot(byears, df["ON-ROAD",], pch=19, type="b", col="dark blue", ylab="ON-ROAD", xlab="Years")
plot(byears, df["NONPOINT",], pch=19, type="b", col="dark green", ylab="NON POINT", xlab="Years")
plot(byears, df["POINT",], pch=19, type="b", col="magenta", ylab="POINT", xlab="Years")
